# # **NumPy**

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

# **1.Installing Numpy**

In [ ]:
pip install NumPy

# **2.Importing NumPy**

In [ ]:
import numpy as np


# **3. Basics of NumPy Arrays**

   **Types of Array:**

   1. One Dimensional Array

   2. Multi-Dimensional Array
 
 
   ***1.One Dimensional Array:***

   A one-dimensional array is a type of linear array.

                |1|2|3|4|

In [ ]:
import numpy as np

# creating list
list = [1, 2, 3, 4]

# creating numpy array
sample_array = np.array(list)

print("List in python : ", list)

print("Numpy Array in python :",sample_array)


 **2.Multi-Dimensional Array:**
 
 
Data in multidimensional arrays are stored in tabular form.

          ____________  
          |1|2|3|4| 5| 
          ____________
          |6|7|8|9|10|
          ____________


In [8]:
import numpy as np
# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1,list_2,list_3])

print("Numpy multi dimensional array in python\n",sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **4.Array Element-wise**

  *Addition
  
  *Substractin
  
  *multiplication

In [12]:
import numpy as np 
  
a = np.array([5, 7, 3, 1]) 
b = np.array([9, 5, 2, 3]) 
  
# array are compatible because of same Dimension 
c = (a + b)
d = (a - b)
e = (a * b)
print(c)
print(d)
print(e)

[14 12  5  4]
[-4  2  1 -2]
[45 35  6  3]


# 5.Array Brodcasting

   Brodcasting is a powerful mechanism that allows NumPy to work array of different shapes during arithmethic operations

In [14]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_1d = np.array([1,0,1])
print(arr_2d + arr_1d)

[[2 2 4]
 [5 5 7]]


# 6.Reshaping array
We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN).
We can reshape and convert it into another array with shape (b1, b2, b3, …, bM).
The only required condition is: a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)

In [15]:
# Reshaping
import numpy as np

array = np.arange(8)
print("Original array : \n", array)

# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)

# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)

# Constructs 3D array
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


***array = np.arange(8)***

***print("Original array : \n", array)***

  * Use code with caution.

  * Creates a NumPy array containing numbers from 0 to 7 (inclusive).

  * Prints the original array.
  

***array = np.arange(8).reshape(2, 4)***

***print("\narray reshaped with 2 rows and 4 columns : \n", array)***

  * Creates a new array by reshaping the previous array into a 2D array with 2 rows and 4 columns. Prints the reshaped array.


***array = np.arange(8).reshape(4 ,2)***

***print("\narray reshaped with 2 rows and 4 columns : \n", array)***
   * This line attempts to reshape the array into a 2x4 array again, but it's incorrect. The total number of elements (8) doesn't match the new shape (4 rows * 2 columns = 8 elements). This will result in an error.
   
  
***array = np.arange(8).reshape(2, 2, 2)***

***print("\nOriginal array reshaped to 3D : \n", array)***
  * Creates a new array by reshaping the original array into a 3D array with 2 layers, each containing a 2x2 matrix.
  * Prints the reshaped 3D array. 

# 7.Slicing and Indexing
  NumPy array can be sliced and indexed just like Python list, but they also support multi-dimension slicing.

In [19]:
#Slicing 1D array
arr = np.array([1,2,3,4,5])
print(arr[1:4])

#Slicing 2D array
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1:,:2])

[2 3 4]
[[4 5]
 [7 8]]


**1D Array**

**arr = np.array([1,2,3,4,5])**

**print(arr[1:4])**

***arr = np.array([1,2,3,4,5]):*** This line creates a NumPy array named *arr* containing the numbers 1 to 5.

***print(arr[1:4]):*** This line prints a slice of the array *arr*.
arr[start:stop:step] is the general syntax for slicing a NumPy array.

  * **start:** The index of the first element to include (inclusive). Default is 0.

  * **stop:** The index of the first element to exclude (exclusive).

  * **step:** The difference between indices to include. Default is 1.

In this case, **start** is 1, **stop** is 4, and **step** is the default 1. So, it will print elements from index 1 (inclusive) up to but not including index 4, which are 2, 3, and 4

----------------------------------------------------------------------------------

**2D Array**
**arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])**

**print(arr_2d[1:,:2])**

  **arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])**: This line creates a 2D NumPy array named arr_2d with three rows and three columns.
  
  **print(arr_2d[1:,:2])**: This line prints a slice of the 2D array arr_2d.
  
 *    For 2D arrays, the slicing syntax is extended to two dimensions: arr[row_slice, column_slice].
 * row_slice: Specifies the range of rows to include.
 * column_slice: Specifies the range of columns to include.
 
  **In this case:**
     * 1: means include all rows from index 1 (inclusive) to the end.
     * :2 means include all columns from the beginning up to but not including index 2 (columns 0 and 1